In [1]:
import os, random, csv

root = "../datasets/LINEMOD/cat/JPEGImages"  # adjust to your images folder
# image_ids = [f.split(".")[0] for f in os.listdir(root) ]



In [5]:
df=pd.read_csv(root2)

In [10]:
import pandas as pd
df = pd.read_csv(r"E:\1Github\Research\paper-implement\datasets\LINEMOD\cat\train_split.csv")
print(df.columns)
# print(df.head())


Index(['000492'], dtype='object')


In [11]:
df.columns

Index(['000492'], dtype='object')

In [14]:
data=np.load("temp/pose1178.npy")

In [15]:
data

array([[-0.973357  , -0.0289978 , -0.227454  , -0.03703931],
       [ 0.130586  ,  0.745279  , -0.65384   , -0.06794026],
       [ 0.188477  , -0.666122  , -0.721636  ,  0.6946476 ]],
      dtype=float32)

In [2]:
import numpy as np
import pandas as pd

In [22]:
R,t=_read_pose_txt(path)

Failed to parse temp/pose0.txt: invalid syntax (<unknown>, line 1)


TypeError: cannot unpack non-iterable NoneType object

In [27]:
R,t=parsed

In [26]:
parsed = _read_pose_txt(path)
if parsed:
    R, t = parsed
    print(R, t)

[[ 0.0950661  0.983309  -0.155129 ]
 [ 0.741596  -0.173913  -0.647911 ]
 [-0.664076  -0.0534489 -0.745752 ]] [ 0.0717302  -0.14907229  1.0606388 ]


In [28]:
R


array([[ 0.0950661,  0.983309 , -0.155129 ],
       [ 0.741596 , -0.173913 , -0.647911 ],
       [-0.664076 , -0.0534489, -0.745752 ]], dtype=float32)

In [24]:
import numpy as np

def _read_pose_txt(path):
    mat = np.loadtxt(path, dtype=np.float32)  # shape (3,4)
    if mat.shape == (3, 4):
        R, t = mat[:, :3], mat[:, 3]
        return R, t
    return None


In [17]:
 import pickle

In [18]:
file_path="temp/test.pkl"

In [29]:
  # with open(file_path, 'rb') as file:
  #       data = pickle.load(file)
  #       print(data)

In [12]:
random.shuffle(image_ids)
split = int(0.8 * len(image_ids))

train_ids = image_ids[:split]
test_ids = image_ids[split:]



In [13]:
with open("../datasets/LINEMOD/cat/train_split.csv", "w", newline="") as f:
    writer = csv.writer(f)
    writer.writerows([[id] for id in train_ids])

with open("../datasets/LINEMOD/cat/test_split.csv", "w", newline="") as f:
    writer = csv.writer(f)
    writer.writerows([[id] for id in test_ids])


In [30]:
import pdb

In [4]:
import os

pose_dir = r"../datasets/LINEMOD/cat/pose"
files = sorted(os.listdir(pose_dir))  

In [5]:
pose_dir

'../datasets/LINEMOD/cat/pose'

In [35]:
# files

In [7]:
# e.g., pose0.txt, pose1.txt, ...
# pdb.set_trace()
for f in files:
    if f.startswith("pose") and f.endswith(".txt"):
        num = int(f[4:-4])  # extract the number after "pose" and before ".txt"
        new_name = f"{num:06d}.txt"  # zero-pad to 6 digits
        old_path = os.path.join(pose_dir, f)
        new_path = os.path.join(pose_dir, new_name)
        os.rename(old_path, new_path)
        print(f"{f} -> {new_name}")


FileNotFoundError: [Errno 2] No such file or directory: '../datasets/LINEMOD/cat/pose/pose0.txt' -> '../datasets/LINEMOD/cat/pose/000000.txt'

## sep 17: testing code

In [15]:
## testing .npy file in contours

In [16]:
path="/home/mimo/Desktop/github/paper-implement/datasets/LINEMOD/cat/noisy_contours/0.npy"

In [17]:
import numpy as np

In [18]:
data = np.load(path)

In [19]:
data.size

702

In [20]:
data.shape

(1, 351, 2)

In [21]:
data

array([[[348. , 194.5],
        [347. , 194.5],
        [346. , 194.5],
        [345. , 194.5],
        [344. , 194.5],
        [343. , 194.5],
        [342. , 194.5],
        [341.5, 194. ],
        [341. , 193.5],
        [340. , 193.5],
        [339.5, 193. ],
        [339. , 192.5],
        [338. , 192.5],
        [337.5, 192. ],
        [337. , 191.5],
        [336.5, 191. ],
        [336. , 190.5],
        [335.5, 190. ],
        [335.5, 189. ],
        [335.5, 188. ],
        [335.5, 187. ],
        [335.5, 186. ],
        [335.5, 185. ],
        [335.5, 184. ],
        [335.5, 183. ],
        [335. , 182.5],
        [334.5, 182. ],
        [334. , 181.5],
        [333. , 181.5],
        [332.5, 181. ],
        [332. , 180.5],
        [331.5, 180. ],
        [331.5, 179. ],
        [331.5, 178. ],
        [331. , 177.5],
        [330.5, 177. ],
        [330.5, 176. ],
        [330.5, 175. ],
        [330.5, 174. ],
        [330.5, 173. ],
        [331. , 172.5],
        [331.5, 